import { redirect } from "next/navigation";
import { TrendingUp } from "lucide-react";

import { FadeIn } from "@/components/fade-in";
import { PageHeader } from "@/components/page-header";
import { RunInsightsButton } from "@/components/run-insights-button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getDashboardData } from "@/lib/dashboard-data";
import { getCurrentSession } from "@/lib/session";
import { formatCurrency } from "@/lib/utils";

export default async function InsightsPage() {
  const session = await getCurrentSession();
  if (!session) {
    redirect("/login");
  }

  const data = await getDashboardData(session.userId);
  const summary = (data.insight?.summaryJson as Record<string, any> | null) ?? null;

  return (
    <div className="space-y-6">
      <FadeIn>
        <PageHeader
          eyebrow="Analytics"
          title="Explain your money patterns"
          description="Understand recurring subscriptions, anomaly alerts, forecasts, behavioral signals, and AI-style recommendations generated by the insights engine."
        />
      </FadeIn>

      <FadeIn delay={0.05}>
        <RunInsightsButton />
      </FadeIn>

      {!summary ? (
        <Card className="border-border bg-card/85">
          <CardContent className="p-6 text-sm text-muted-foreground">
            Upload transactions first so the insights engine has data to analyze.
          </CardContent>
        </Card>
      ) : (
        <>
          <div className="grid gap-6 xl:grid-cols-3">
            <FadeIn delay={0.08}>
              <Card className="border-border bg-card/85">
                <CardHeader>
                  <CardTitle className="font-heading text-2xl">Smart insights</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {summary.smart_insights?.map((item: string) => (
                    <div key={item} className="rounded-2xl border bg-slate-50 p-4 text-sm text-slate-700">
                      {item}
                    </div>
                  ))}
                </CardContent>
              </Card>
            </FadeIn>

            <FadeIn delay={0.12}>
              <Card className="border-border bg-card/85">
                <CardHeader>
                  <CardTitle className="font-heading text-2xl">Waste signals</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {(summary.waste_signals?.length ?? 0) === 0 ? (
                    <p className="text-sm text-muted-foreground">No major waste signals detected.</p>
                  ) : (
                    summary.waste_signals.map((item: string) => (
                      <div key={item} className="rounded-2xl border bg-amber-50 p-4 text-sm text-amber-800">
                        {item}
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>
            </FadeIn>

            <FadeIn delay={0.16}>
              <Card className="border-border bg-card/85">
                <CardHeader>
                  <CardTitle className="font-heading text-2xl">Forecast</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="rounded-3xl bg-slate-950 p-6 text-white">
                    <p className="text-xs uppercase tracking-[0.18em] text-slate-400">Next month projection</p>
                    <p className="mt-3 font-heading text-5xl font-semibold">
                      {formatCurrency(summary.forecast_next_month ?? 0)}
                    </p>
                    <p className="mt-3 inline-flex items-center text-sm text-slate-300">
                      <TrendingUp className="mr-2 h-4 w-4 text-primary" />
                      Updated from recent month-over-month spending behavior.
                    </p>
                  </div>
                </CardContent>
              </Card>
            </FadeIn>
          </div>

          <div className="grid gap-6 xl:grid-cols-2">
            <FadeIn delay={0.2}>
              <Card className="border-border bg-card/85">
                <CardHeader>
                  <CardTitle className="font-heading text-2xl">Recurring expenses</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {(summary.recurring_expenses?.length ?? 0) === 0 ? (
                    <p className="text-sm text-muted-foreground">No recurring patterns detected yet.</p>
                  ) : (
                    summary.recurring_expenses.map((item: { merchant: string; amount: number; cadence: string }) => (
                      <div key={`${item.merchant}-${item.amount}`} className="rounded-2xl border bg-slate-50 p-4">
                        <div className="flex items-center justify-between gap-4">
                          <div>
                            <p className="font-medium">{item.merchant}</p>
                            <p className="text-sm text-muted-foreground">{item.cadence} recurring charge</p>
                          </div>
                          <Badge variant="warning">{formatCurrency(item.amount)}</Badge>
                        </div>
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>
            </FadeIn>

            <FadeIn delay={0.24}>
              <Card className="border-border bg-card/85">
                <CardHeader>
                  <CardTitle className="font-heading text-2xl">Anomaly detection</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {(summary.anomalies?.length ?? 0) === 0 ? (
                    <p className="text-sm text-muted-foreground">No anomalies flagged in the latest run.</p>
                  ) : (
                    summary.anomalies.map((item: { merchant: string; amount: number; date: string; reason: string }) => (
                      <div key={`${item.merchant}-${item.date}-${item.amount}`} className="rounded-2xl border bg-rose-50 p-4">
                        <div className="flex items-center justify-between gap-4">
                          <p className="font-medium text-rose-900">{item.merchant}</p>
                          <Badge variant="danger">{formatCurrency(item.amount)}</Badge>
                        </div>
                        <p className="mt-2 text-sm text-rose-700">{item.reason}</p>
                        <p className="mt-1 text-xs uppercase tracking-[0.16em] text-rose-500">{item.date}</p>
                      </div>
                    ))
                  )}
                </CardContent>
              </Card>
            </FadeIn>
          </div>

          <FadeIn delay={0.28}>
            <Card className="border-border bg-card/85">
              <CardHeader>
                <CardTitle className="font-heading text-2xl">Recommendations</CardTitle>
              </CardHeader>
              <CardContent className="grid gap-3 md:grid-cols-2">
                {summary.recommendations?.map((item: string) => (
                  <div key={item} className="rounded-2xl border bg-emerald-50 p-4 text-sm text-emerald-900">
                    {item}
                  </div>
                ))}
              </CardContent>
            </Card>
          </FadeIn>
        </>
      )}
    </div>
  );
}
